
INSERT INTO customers (CustomerID, FirstName, LastName, EmailAddress, Phone) VALUES (1, 'Maddie', 'Williams', 'maddie.williams@gmail.com', '0040745234234');
INSERT INTO customers (CustomerID, FirstName, LastName, EmailAddress, Phone) VALUES (2, 'Henry', 'Church', 'henry.church@gmail.com', '0040745256837');
INSERT INTO customers (CustomerID, FirstName, LastName, EmailAddress, Phone) VALUES (3, 'Margot', 'Robbie', 'margot.robbie@gmail.com', '0040752485623');
INSERT INTO customers (CustomerID, FirstName, LastName, EmailAddress, Phone) VALUES (4, 'Moses', 'Elastair', 'moses.elastair@gmail.com', '0040755364528');
INSERT INTO customers (CustomerID, FirstName, LastName, EmailAddress, Phone) VALUES (5, 'Samuel', 'Jackson', 'samuel.jackson@gmail.com', '0040743645819');
INSERT INTO customers (CustomerID, FirstName, LastName, EmailAddress, Phone) VALUES (6, 'Asa', 'Mercury', 'asa.mercury@gmail.com', '0040752745992');
INSERT INTO customers (CustomerID, FirstName, LastName, EmailAddress, Phone) VALUES (7, 'Rollo', 'Weeks', 'rollo.weeks@gmail.com', '0040743458732');
INSERT INTO customers (CustomerID, FirstName, LastName, EmailAddress, Phone) VALUES (8, 'Sarah', 'Jones', 'sarah.jones@gmail.com', '0040756738456');
INSERT INTO customers (CustomerID, FirstName, LastName, EmailAddress, Phone) VALUES (9, 'Mary', 'Brown', 'mary.brown@gmail.com', '0040748346578');
INSERT INTO customers (CustomerID, FirstName, LastName, EmailAddress, Phone) VALUES (10, 'Perdita', 'Everly', 'perdita.everly@gmail.com', '0040756734599');
INSERT INTO customers (CustomerID, FirstName, LastName, EmailAddress, Phone) VALUES (11, 'John', 'Smith', 'john.smith@gmail.com', '0040752384582');
INSERT INTO customers (CustomerID, FirstName, LastName, EmailAddress, Phone) VALUES (12, 'Robin', 'Walcott', 'robin.walcott@gmail.com', '0040743745345');
INSERT INTO customers (CustomerID, FirstName, LastName, EmailAddress, Phone) VALUES (13, 'Emily', 'Winchester', 'emily.winchester@gmail.com', '0040752332466');
INSERT INTO customers (CustomerID, FirstName, LastName, EmailAddress, Phone) VALUES (14, 'William', 'Adams', 'william.adams@gmail.com', '0040745328469');
INSERT INTO customers (CustomerID, FirstName, LastName, EmailAddress, Phone) VALUES (15, 'Sylvia', 'Evans', 'sylvia.evans@gmail.com', '0040753756283');

INSERT INTO "customers.registered" (CustomerID, DeliveryAddressID, FidelityRewardPoints, NewsletterSubscription) VALUES (1, 1, 100, 0);
INSERT INTO "customers.registered" (CustomerID, DeliveryAddressID, FidelityRewardPoints, NewsletterSubscription) VALUES (2, 2, 120, 1);
INSERT INTO "customers.registered" (CustomerID, DeliveryAddressID, FidelityRewardPoints, NewsletterSubscription) VALUES (3, 3, 50, 1);
INSERT INTO "customers.registered" (CustomerID, DeliveryAddressID, FidelityRewardPoints, NewsletterSubscription) VALUES (4, 4, 75, 1);
INSERT INTO "customers.registered" (CustomerID, DeliveryAddressID, FidelityRewardPoints, NewsletterSubscription) VALUES (5, 5, 250, 0);
INSERT INTO "customers.registered" (CustomerID, DeliveryAddressID, FidelityRewardPoints, NewsletterSubscription) VALUES (6, 6, 0, 1);
INSERT INTO "customers.registered" (CustomerID, DeliveryAddressID, FidelityRewardPoints, NewsletterSubscription) VALUES (7, 7, 100, 1);
INSERT INTO "customers.registered" (CustomerID, DeliveryAddressID, FidelityRewardPoints, NewsletterSubscription) VALUES (8, 8, 130, 0);
INSERT INTO "customers.registered" (CustomerID, DeliveryAddressID, FidelityRewardPoints, NewsletterSubscription) VALUES (9, 9, 280, 1);
INSERT INTO "customers.registered" (CustomerID, DeliveryAddressID, FidelityRewardPoints, NewsletterSubscription) VALUES (10, 10, 175, 0);

INSERT INTO "customers.registered_login" (CustomerID, Username, Password) VALUES (1, 'MaddieWilliams01', 'password1');
INSERT INTO "customers.registered_login" (CustomerID, Username, Password) VALUES (2, 'HenryChurch02', 'password2');
INSERT INTO "customers.registered_login" (CustomerID, Username, Password) VALUES (3, 'MargotRobbie03', 'password3');
INSERT INTO "customers.registered_login" (CustomerID, Username, Password) VALUES (4, 'MosesElastair04', 'password4');
INSERT INTO "customers.registered_login" (CustomerID, Username, Password) VALUES (5, 'SamuelJackson05', 'password5');
INSERT INTO "customers.registered_login" (CustomerID, Username, Password) VALUES (6, 'AsaMercury06', 'password6');
INSERT INTO "customers.registered_login" (CustomerID, Username, Password) VALUES (7, 'RolloWeeks07', 'password7');
INSERT INTO "customers.registered_login" (CustomerID, Username, Password) VALUES (8, 'SarahJones08', 'password8');
INSERT INTO "customers.registered_login" (CustomerID, Username, Password) VALUES (9, 'MaryBrown09', 'password9');
INSERT INTO "customers.registered_login" (CustomerID, Username, Password) VALUES (10, 'PerditaEverly10', 'password10');

INSERT INTO active_ingredient (id, active_ingredient) VALUES (1, 'Glucosamine');
INSERT INTO active_ingredient (id, active_ingredient) VALUES (2, 'Vitamin B12');
INSERT INTO active_ingredient (id, active_ingredient) VALUES (3, 'Calcium');
INSERT INTO active_ingredient (id, active_ingredient) VALUES (4, 'Omega 3');
INSERT INTO active_ingredient (id, active_ingredient) VALUES (5, 'Fish Oil');
INSERT INTO active_ingredient (id, active_ingredient) VALUES (6, 'Vitamin E');
INSERT INTO active_ingredient (id, active_ingredient) VALUES (7, 'Praziquantel');
INSERT INTO active_ingredient (id, active_ingredient) VALUES (8, 'Vitamin D');
INSERT INTO active_ingredient (id, active_ingredient) VALUES (9, 'Iron');

INSERT INTO food_flavour (id, flavour) VALUES (1, 'Chicken');
INSERT INTO food_flavour (id, flavour) VALUES (2, 'Beef');
INSERT INTO food_flavour (id, flavour) VALUES (3, 'Salmon');
INSERT INTO food_flavour (id, flavour) VALUES (4, 'Lamb');
INSERT INTO food_flavour (id, flavour) VALUES (5, 'Turkey');
INSERT INTO food_flavour (id, flavour) VALUES (6, 'Vegetables');

INSERT INTO food_form (id, food_form) VALUES (1, 'Dry Food');
INSERT INTO food_form (id, food_form) VALUES (2, 'Wet Food');
INSERT INTO food_form (id, food_form) VALUES (3, 'Raw Food');
INSERT INTO food_form (id, food_form) VALUES (4, 'Dehydrated Food');
INSERT INTO food_form (id, food_form) VALUES (5, 'Canned Food');

INSERT INTO food_type (id, food_type) VALUES (1, 'Dry Dog Food');
INSERT INTO food_type (id, food_type) VALUES (2, 'Premium Food');
INSERT INTO food_type (id, food_type) VALUES (3, 'Veterinary Diets');
INSERT INTO food_type (id, food_type) VALUES (4, 'Treats');

INSERT INTO health_feature (id, health_feature) VALUES (1, 'Hip&Joint Support');
INSERT INTO health_feature (id, health_feature) VALUES (2, 'Skin&Coat Health');
INSERT INTO health_feature (id, health_feature) VALUES (3, 'High-Energy');
INSERT INTO health_feature (id, health_feature) VALUES (4, 'Weight Management');
INSERT INTO health_feature (id, health_feature) VALUES (5, 'Digestive Health');
INSERT INTO health_feature (id, health_feature) VALUES (6, 'Appetite Stimulation');
INSERT INTO health_feature (id, health_feature) VALUES (7, 'Heart Care');
INSERT INTO health_feature (id, health_feature) VALUES (8, 'Dental Care&Breadth');
INSERT INTO health_feature (id, health_feature) VALUES (9, 'Itch&Redness Remedy');
INSERT INTO health_feature (id, health_feature) VALUES (10, 'Eye care');
INSERT INTO health_feature (id, health_feature) VALUES (11, 'Vitamins&Minerals');
INSERT INTO health_feature (id, health_feature) VALUES (12, 'Anti-Parasitic');
INSERT INTO health_feature (id, health_feature) VALUES (13, 'Immune Support');

INSERT INTO leash_type (id, leash_type) VALUES (1, 'Rectractable');
INSERT INTO leash_type (id, leash_type) VALUES (2, 'Adjustable');
INSERT INTO leash_type (id, leash_type) VALUES (3, 'Step in');
INSERT INTO leash_type (id, leash_type) VALUES (4, 'Hands-free');
INSERT INTO leash_type (id, leash_type) VALUES (5, 'Double Leash');

INSERT INTO medication_form (id, medication_form) VALUES (1, 'Powder');
INSERT INTO medication_form (id, medication_form) VALUES (2, 'Soft Chew');
INSERT INTO medication_form (id, medication_form) VALUES (3, 'Solution');
INSERT INTO medication_form (id, medication_form) VALUES (4, 'Spray');
INSERT INTO medication_form (id, medication_form) VALUES (5, 'Ointment');
INSERT INTO medication_form (id, medication_form) VALUES (6, 'Chewable Tablet');

INSERT INTO medication_type (id, type) VALUES (1, 'non-prescription');
INSERT INTO medication_type (id, type) VALUES (2, 'prescription');

INSERT INTO orders (OrderID, CustomerID, OrderStatusID, Total, DeliveryAddressID, OrderDate, PaymentTypeID) VALUES (1, 1, 1, 270, 1, '2020-11-09', 1);
INSERT INTO orders (OrderID, CustomerID, OrderStatusID, Total, DeliveryAddressID, OrderDate, PaymentTypeID) VALUES (2, 2, 2, 210, 2, '2020-11-09', 2);
INSERT INTO orders (OrderID, CustomerID, OrderStatusID, Total, DeliveryAddressID, OrderDate, PaymentTypeID) VALUES (3, 3, 3, 145, 3, '2020-11-10', 2);
INSERT INTO orders (OrderID, CustomerID, OrderStatusID, Total, DeliveryAddressID, OrderDate, PaymentTypeID) VALUES (4, 4, 4, 145, 4, '2020-11-10', 1);
INSERT INTO orders (OrderID, CustomerID, OrderStatusID, Total, DeliveryAddressID, OrderDate, PaymentTypeID) VALUES (5, 5, 1, 95, 5, '2020-11-11', 2);
INSERT INTO orders (OrderID, CustomerID, OrderStatusID, Total, DeliveryAddressID, OrderDate, PaymentTypeID) VALUES (6, 6, 2, 25, 6, '2020-11-11', 2);
INSERT INTO orders (OrderID, CustomerID, OrderStatusID, Total, DeliveryAddressID, OrderDate, PaymentTypeID) VALUES (7, 7, 3, 30, 7, '2020-11-12', 2);
INSERT INTO orders (OrderID, CustomerID, OrderStatusID, Total, DeliveryAddressID, OrderDate, PaymentTypeID) VALUES (8, 8, 5, 70, 8, '2020-11-12', 2);
INSERT INTO orders (OrderID, CustomerID, OrderStatusID, Total, DeliveryAddressID, OrderDate, PaymentTypeID) VALUES (9, 9, 1, 59, 9, '2020-11-13', 1);
INSERT INTO orders (OrderID, CustomerID, OrderStatusID, Total, DeliveryAddressID, OrderDate, PaymentTypeID) VALUES (10, 10, 2, 60, 10, '2020-11-13', 2);
INSERT INTO orders (OrderID, CustomerID, OrderStatusID, Total, DeliveryAddressID, OrderDate, PaymentTypeID) VALUES (11, 11, 3, 130, 11, '2020-11-14', 2);
INSERT INTO orders (OrderID, CustomerID, OrderStatusID, Total, DeliveryAddressID, OrderDate, PaymentTypeID) VALUES (12, 12, 1, 30, 12, '2020-11-14', 2);
INSERT INTO orders (OrderID, CustomerID, OrderStatusID, Total, DeliveryAddressID, OrderDate, PaymentTypeID) VALUES (13, 13, 2, 35, 13, '2020-11-15', 1);
INSERT INTO orders (OrderID, CustomerID, OrderStatusID, Total, DeliveryAddressID, OrderDate, PaymentTypeID) VALUES (14, 14, 3, 20, 14, '2020-11-15', 2);
INSERT INTO orders (OrderID, CustomerID, OrderStatusID, Total, DeliveryAddressID, OrderDate, PaymentTypeID) VALUES (15, 15, 1, 25, 15, '2020-11-16', 1);

INSERT INTO "orders.delivery_address" (DeliveryAddressID, CountryID, City, Street, HouseNr) VALUES (1, 459, 'London', 'Shaftesbury Avenue', 11);
INSERT INTO "orders.delivery_address" (DeliveryAddressID, CountryID, City, Street, HouseNr) VALUES (2, 459, 'Yorkshire', 'New Cathedral Street', 12);
INSERT INTO "orders.delivery_address" (DeliveryAddressID, CountryID, City, Street, HouseNr) VALUES (3, 338, 'Dublin', 'Market Street', 13);
INSERT INTO "orders.delivery_address" (DeliveryAddressID, CountryID, City, Street, HouseNr) VALUES (4, 459, 'Manchester', 'Kingsway', 14);
INSERT INTO "orders.delivery_address" (DeliveryAddressID, CountryID, City, Street, HouseNr) VALUES (5, 459, 'Cambridge', 'Spring Gardens', 15);
INSERT INTO "orders.delivery_address" (DeliveryAddressID, CountryID, City, Street, HouseNr) VALUES (6, 459, 'Liverpool', 'Baker Street', 16);
INSERT INTO "orders.delivery_address" (DeliveryAddressID, CountryID, City, Street, HouseNr) VALUES (7, 459, 'London', 'Princess Street', 17);
INSERT INTO "orders.delivery_address" (DeliveryAddressID, CountryID, City, Street, HouseNr) VALUES (8, 309, 'Marseille', 'Rue de l’Eglise', 18);
INSERT INTO "orders.delivery_address" (DeliveryAddressID, CountryID, City, Street, HouseNr) VALUES (9, 459, 'Inverness', 'Portland Street', 19);
INSERT INTO "orders.delivery_address" (DeliveryAddressID, CountryID, City, Street, HouseNr) VALUES (10, 309, 'Paris', 'Rue Vieille Du Temple', 20);
INSERT INTO "orders.delivery_address" (DeliveryAddressID, CountryID, City, Street, HouseNr) VALUES (11, 316, 'Hamburg', 'Deichstraße', 21);
INSERT INTO "orders.delivery_address" (DeliveryAddressID, CountryID, City, Street, HouseNr) VALUES (12, 316, 'Berlin', 'Oranienburger Strasse', 22);
INSERT INTO "orders.delivery_address" (DeliveryAddressID, CountryID, City, Street, HouseNr) VALUES (13, 309, 'Lyon', 'Rue De La Huchette ', 23);
INSERT INTO "orders.delivery_address" (DeliveryAddressID, CountryID, City, Street, HouseNr) VALUES (14, 338, 'Belfast', 'Abbey Street', 24);
INSERT INTO "orders.delivery_address" (DeliveryAddressID, CountryID, City, Street, HouseNr) VALUES (15, 338, 'Limerick', 'Bridge Street ', 25);

INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (238, 'AFGHANISTAN', 'AF');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (239, 'ALBANIA', 'AL');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (240, 'ALGERIA', 'DZ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (241, 'AMERICAN SAMOA', 'AS');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (242, 'ANDORRA', 'AD');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (243, 'ANGOLA', 'AO');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (244, 'ANTARCTICA', 'AQ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (245, 'ANTIGUA AND BARBUDA', 'AG');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (246, 'ARGENTINA', 'AR');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (247, 'ARMENIA', 'AM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (248, 'ARUBA', 'AW');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (249, 'AUSTRALIA', 'AU');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (250, 'AUSTRIA', 'AT');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (251, 'AZERBAIJAN', 'AZ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (252, 'BAHAMAS', 'BS');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (253, 'BAHRAIN', 'BH');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (254, 'BANGLADESH', 'BD');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (255, 'BARBADOS', 'BB');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (256, 'BELARUS', 'BY');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (257, 'BELGIUM', 'BE');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (258, 'BELIZE', 'BZ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (259, 'BENIN', 'BJ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (260, 'BERMUDA', 'BM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (261, 'BHUTAN', 'BT');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (262, 'BOLIVIA', 'BO');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (263, 'BOSNIA AND HERZEGOVINA', 'BA');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (264, 'BOTSWANA', 'BW');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (265, 'BOUVET ISLAND', 'BV');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (266, 'BRAZIL', 'BR');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (267, 'BRITISH INDIAN OCEAN TERRITORY', 'IO');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (268, 'BRUNEI DARUSSALAM', 'BN');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (269, 'BULGARIA', 'BG');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (270, 'BURKINA FASO', 'BF');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (271, 'BURUNDI', 'BI');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (272, 'CAMBODIA', 'KH');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (273, 'CAMEROON', 'CM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (274, 'CANADA', 'CA');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (275, 'CAPE VERDE', 'CV');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (276, 'CAYMAN ISLANDS', 'KY');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (277, 'CENTRAL AFRICAN REPUBLIC', 'CF');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (278, 'CHAD', 'TD');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (279, 'CHILE', 'CL');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (280, 'CHINA', 'CN');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (281, 'CHRISTMAS ISLAND', 'CX');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (282, 'COCOS (KEELING) ISLANDS', 'CC');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (283, 'COLOMBIA', 'CO');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (284, 'COMOROS', 'KM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (285, 'CONGO', 'CG');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (286, 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'CD');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (287, 'COOK ISLANDS', 'CK');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (288, 'COSTA RICA', 'CR');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (289, 'COTE D''IVOIRE', 'CI');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (290, 'CROATIA', 'HR');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (291, 'CUBA', 'CU');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (292, 'CYPRUS', 'CY');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (293, 'CZECH REPUBLIC', 'CZ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (294, 'DENMARK', 'DK');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (295, 'DJIBOUTI', 'DJ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (296, 'DOMINICA', 'DM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (297, 'DOMINICAN REPUBLIC', 'DO');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (298, 'ECUADOR', 'EC');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (299, 'EGYPT', 'EG');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (300, 'EL SALVADOR', 'SV');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (301, 'EQUATORIAL GUINEA', 'GQ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (302, 'ERITREA', 'ER');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (303, 'ESTONIA', 'EE');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (304, 'ETHIOPIA', 'ET');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (305, 'FALKLAND ISLANDS (MALVINAS)', 'FK');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (306, 'FAROE ISLANDS', 'FO');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (307, 'FIJI', 'FJ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (308, 'FINLAND', 'FI');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (309, 'FRANCE', 'FR');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (310, 'FRENCH GUIANA', 'GF');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (311, 'FRENCH POLYNESIA', 'PF');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (312, 'FRENCH SOUTHERN TERRITORIES', 'TF');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (313, 'GABON', 'GA');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (314, 'GAMBIA', 'GM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (315, 'GEORGIA', 'GE');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (316, 'GERMANY', 'DE');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (317, 'GHANA', 'GH');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (318, 'GIBRALTAR', 'GI');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (319, 'GREECE', 'GR');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (320, 'GREENLAND', 'GL');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (321, 'GRENADA', 'GD');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (322, 'GUADELOUPE', 'GP');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (323, 'GUAM', 'GU');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (324, 'GUATEMALA', 'GT');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (325, 'GUINEA', 'GN');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (326, 'GUINEA-BISSAU', 'GW');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (327, 'GUYANA', 'GY');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (328, 'HAITI', 'HT');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (329, 'HEARD ISLAND AND MCDONALD ISLANDS', 'HM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (330, 'HONDURAS', 'HN');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (331, 'HONG KONG', 'HK');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (332, 'HUNGARY', 'HU');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (333, 'ICELAND', 'IS');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (334, 'INDIA', 'IN');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (335, 'INDONESIA', 'ID');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (336, 'IRAN, ISLAMIC REPUBLIC OF', 'IR');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (337, 'IRAQ', 'IQ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (338, 'IRELAND', 'IE');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (339, 'ISRAEL', 'IL');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (340, 'ITALY', 'IT');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (341, 'JAMAICA', 'JM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (342, 'JAPAN', 'JP');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (343, 'JORDAN', 'JO');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (344, 'KAZAKHSTAN', 'KZ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (345, 'KENYA', 'KE');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (346, 'KIRIBATI', 'KI');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (347, 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 'KP');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (348, 'KOREA, REPUBLIC OF', 'KR');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (349, 'KUWAIT', 'KW');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (350, 'KYRGYZSTAN', 'KG');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (351, 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'LA');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (352, 'LATVIA', 'LV');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (353, 'LEBANON', 'LB');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (354, 'LESOTHO', 'LS');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (355, 'LIBERIA', 'LR');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (356, 'LIBYAN ARAB JAMAHIRIYA', 'LY');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (357, 'LIECHTENSTEIN', 'LI');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (358, 'LITHUANIA', 'LT');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (359, 'LUXEMBOURG', 'LU');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (360, 'MACAO', 'MO');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (361, 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'MK');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (362, 'MADAGASCAR', 'MG');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (363, 'MALAWI', 'MW');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (364, 'MALAYSIA', 'MY');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (365, 'MALDIVES', 'MV');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (366, 'MALI', 'ML');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (367, 'MALTA', 'MT');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (368, 'MARSHALL ISLANDS', 'MH');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (369, 'MARTINIQUE', 'MQ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (370, 'MAURITANIA', 'MR');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (371, 'MAURITIUS', 'MU');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (372, 'MAYOTTE', 'YT');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (373, 'MEXICO', 'MX');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (374, 'MICRONESIA, FEDERATED STATES OF', 'FM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (375, 'MOLDOVA, REPUBLIC OF', 'MD');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (376, 'MONACO', 'MD');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (377, 'MONGOLIA', 'MN');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (378, 'MONTSERRAT', 'MS');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (379, 'MOROCCO', 'MA');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (380, 'MOZAMBIQUE', 'MZ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (381, 'MYANMAR', 'MM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (382, 'NAMIBIA', 'NA');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (383, 'NAURU', 'NR');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (384, 'NEPAL', 'NP');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (385, 'NETHERLANDS', 'NL');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (386, 'NETHERLANDS ANTILLES', 'AN');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (387, 'NEW CALEDONIA', 'NC');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (388, 'NEW ZEALAND', 'NZ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (389, 'NICARAGUA', 'NI');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (390, 'NIGER', 'NE');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (391, 'NIGERIA', 'NG');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (392, 'NIUE', 'NU');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (393, 'NORFOLK ISLAND', 'NF');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (394, 'NORTHERN MARIANA ISLANDS', 'MP');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (395, 'NORWAY', 'NO');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (396, 'OMAN', 'OM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (397, 'PAKISTAN', 'PK');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (398, 'PALAU', 'PW');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (399, 'PALESTINIAN TERRITORY, OCCUPIED', 'PS');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (400, 'PANAMA', 'PA');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (401, 'PAPUA NEW GUINEA', 'PG');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (402, 'PARAGUAY', 'PY');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (403, 'PERU', 'PE');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (404, 'PHILIPPINES', 'PH');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (405, 'PITCAIRN', 'PN');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (406, 'POLAND', 'PL');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (407, 'PUERTO RICO', 'PR');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (408, 'QATAR', 'QA');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (409, 'R�UNION', 'RE');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (410, 'ROMANIA', 'RO');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (411, 'RUSSIAN FEDERATION', 'RU');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (412, 'RWANDA', 'RW');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (413, 'SAINT HELENA', 'SH');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (414, 'SAINT KITTS AND NEVIS', 'KN');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (415, 'SAINT LUCIA', 'LC');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (416, 'SAINT PIERRE AND MIQUELON', 'PM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (417, 'SAINT VINCENT AND THE GRENADINES', 'VC');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (418, 'SAMOA', 'WS');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (419, 'SAN MARINO', 'SM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (420, 'SAO TOME AND PRINCIPE', 'ST');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (421, 'SAUDI ARABIA', 'SA');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (422, 'SENEGAL', 'SN');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (423, 'SERBIA AND MONTENEGRO', 'CS');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (424, 'SEYCHELLES', 'SC');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (425, 'SIERRA LEONE', 'SL');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (426, 'SINGAPORE', 'SG');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (427, 'SLOVAKIA', 'SK');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (428, 'SLOVENIA', 'SI');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (429, 'SOLOMON ISLANDS', 'SB');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (430, 'SOMALIA', 'SO');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (431, 'SOUTH AFRICA', 'ZA');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (432, 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'GS');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (433, 'SPAIN', 'ES');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (434, 'SRI LANKA', 'LK');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (435, 'SUDAN', 'SD');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (436, 'SURINAME', 'SR');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (437, 'SVALBARD AND JAN MAYEN', 'SJ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (438, 'SWAZILAND', 'SZ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (439, 'SWEDEN', 'SE');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (440, 'SWITZERLAND', 'CH');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (441, 'SYRIAN ARAB REPUBLIC', 'SY');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (442, 'TAIWAN, PROVINCE OF CHINA', 'TW');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (443, 'TAJIKISTAN', 'TJ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (444, 'TANZANIA, UNITED REPUBLIC OF', 'TZ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (445, 'THAILAND', 'TH');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (446, 'TIMOR-LESTE', 'TL');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (447, 'TOGO', 'TG');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (448, 'TOKELAU', 'TK');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (449, 'TONGA', 'TO');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (450, 'TRINIDAD AND TOBAGO', 'TT');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (451, 'TUNISIA', 'TN');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (452, 'TURKEY', 'TR');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (453, 'TURKMENISTAN', 'TM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (454, 'TURKS AND CAICOS ISLANDS', 'TC');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (455, 'TUVALU', 'TV');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (456, 'UGANDA', 'UG');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (457, 'UKRAINE', 'UA');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (458, 'UNITED ARAB EMIRATES', 'AE');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (459, 'UNITED KINGDOM', 'GB');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (460, 'UNITED STATES', 'US');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (461, 'UNITED STATES MINOR OUTLYING ISLANDS', 'UM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (462, 'URUGUAY', 'UY');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (463, 'UZBEKISTAN', 'UZ');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (464, 'VANUATU', 'VU');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (465, 'VENEZUELA', 'VE');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (466, 'VIET NAM', 'VN');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (467, 'VIRGIN ISLANDS, BRITISH', 'VG');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (468, 'VIRGIN ISLANDS, U.S.', 'VI');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (469, 'WALLIS AND FUTUNA', 'WF');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (470, 'WESTERN SAHARA', 'EH');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (471, 'YEMEN', 'YE');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (472, 'ZAMBIA', 'ZM');
INSERT INTO "orders.delivery_address_countries" (CountryID, CountryName, ISOCode) VALUES (473, 'ZIMBABWE', 'ZW');

INSERT INTO "orders.payment_type" (PaymentTypeID, PaymentType) VALUES (1, 'Cash on delivery');
INSERT INTO "orders.payment_type" (PaymentTypeID, PaymentType) VALUES (2, 'Online with credit card');

INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (1, 1, 1);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (1, 2, 2);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (2, 3, 3);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (3, 4, 1);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (4, 5, 2);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (4, 6, 3);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (5, 7, 1);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (6, 8, 2);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (7, 9, 3);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (8, 10, 1);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (8, 11, 2);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (9, 12, 3);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (9, 13, 1);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (10, 14, 2);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (11, 15, 3);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (11, 16, 1);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (12, 17, 2);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (13, 18, 3);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (14, 19, 1);
INSERT INTO "orders.products" (OrderID, ProductID, ProductQuantity) VALUES (15, 20, 1);

INSERT INTO order_status (id, order_status) VALUES (1, 'PENDING');
INSERT INTO order_status (id, order_status) VALUES (2, 'PROCESSING');
INSERT INTO order_status (id, order_status) VALUES (3, 'SHIPPED');
INSERT INTO order_status (id, order_status) VALUES (4, 'RETURNED');
INSERT INTO order_status (id, order_status) VALUES (5, 'CANCELED');

INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (1, 'Dry Dog Food', 120, 1, 1, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (2, 'Dehydrated Dog Food', 150, 2, 2, 5);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (3, 'Purina Pro Plan', 210, 1, 3, 5);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (4, 'Premium Dry Dog Food', 145, 1, 4, 5);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (5, 'Wet Dog Food Variety', 80, 2, 5, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (6, 'Hill''s Science Diet', 65, 1, 5, 3);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (7, 'Turkey Chunks Raw Dog Food', 95, 2, 3, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (8, 'Dehydrated Dog Food', 25, 1, 2, 2);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (9, 'Divine Delights', 30, 1, 1, 3);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (10, 'Mediterranean Style Canned Dog Food', 25, 2, 3, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (11, 'HeartGuard Plus Powder Supplements', 45, 1, 6, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (12, 'DentaLife Dentastix Chewable Treats', 34, 1, 2, 5);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (13, 'First-Aid Pet Spray', 25, 1, 2, 3);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (14, 'Wound & Skin Hydrogel Pet Cream', 60, 2, 3, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (15, 'First-Aid Pet Spray Eye Protection', 80, 1, 4, 5);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (16, 'MultiVitamin Dog Supplement', 50, 1, 5, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (17, 'Ear-Mite Protection', 30, 2, 7, 2);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (18, 'Canine Health Chewable Tablets', 35, 1, 2, 3);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (19, 'Dewormer Chewable Tablet', 20, 1, 1, 3);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (20, 'Essential Vitamins&Minerals Supplement', 25, 2, 7, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (21, 'Ring Dog Chew Toy', 30, 1, 8, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (22, 'Snuggle Plush Pet Toy', 25, 1, 9, 3);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (23, 'Rubber Ball', 35, 1, 2, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (24, 'Leather Rope Toy', 24, 1, 1, 2);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (25, 'Frisbee Dog Toy', 10, 1, 7, 3);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (26, 'Teething Pacifier Puppy Chew Toy', 20, 2, 3, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (27, 'Plush Teddy Bear Toy', 30, 1, 4, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (28, 'Indoor Ball Dog Toy', 40, 1, 5, 5);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (29, 'Plush With Inside Rope Toy', 25, 1, 7, 3);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (30, 'Activity Flip Board Strategy Dog Toy', 15, 2, 8, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (31, 'Rectractable Leash', 50, 1, 7, 5);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (32, 'Adjustable Trainer Leash', 45, 1, 2, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (33, 'Comfortable Leash', 60, 1, 1, 2);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (34, 'Reflective Rope Dog Leash', 80, 2, 7, 3);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (35, 'Ultrasecure Leash', 65, 1, 8, 3);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (36, 'Groomer''s Best Brush', 20, 2, 2, 3);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (37, 'Hand Gloves Deshedding Aid', 15, 1, 3, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (38, 'Lavender&Mint Shampoo', 25, 1, 4, 4);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (39, 'Aloe Vera Ointment for Dogs', 30, 1, 1, 5);
INSERT INTO products (ProductID, ProductName, Price, AvailabilityID, BrandID, CustomerRating) VALUES (40, 'Best Nail Clipper for Dogs', 35, 2, 7, 3);

INSERT INTO "products.availability" (AvailabilityID, Availability) VALUES (1, 'in-stock');
INSERT INTO "products.availability" (AvailabilityID, Availability) VALUES (2, 'out-of-stock');

INSERT INTO "products.brands" (BrandID, BrandName) VALUES (1, 'Dog Chow');
INSERT INTO "products.brands" (BrandID, BrandName) VALUES (2, 'Pedigree');
INSERT INTO "products.brands" (BrandID, BrandName) VALUES (3, 'Purina');
INSERT INTO "products.brands" (BrandID, BrandName) VALUES (4, 'Royal Canine');
INSERT INTO "products.brands" (BrandID, BrandName) VALUES (5, 'Hill''s Prescription Diet');
INSERT INTO "products.brands" (BrandID, BrandName) VALUES (6, 'HeartGuard');
INSERT INTO "products.brands" (BrandID, BrandName) VALUES (7, 'Zestry Paws');
INSERT INTO "products.brands" (BrandID, BrandName) VALUES (8, 'Frisco');
INSERT INTO "products.brands" (BrandID, BrandName) VALUES (9, 'GoDog');

INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (1, 'Gluten Free', 'Hip&Joint Support');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (2, 'High Protein', 'Skin&Coat Health');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (3, 'High Protein', 'High-Energy');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (4, 'No corn/wheat/soy', 'Weight Management');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (5, 'Sensitive Digestion', 'Digestive Health');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (6, 'Sensitive Digestion', 'Appetite Stimulation');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (7, 'Grain Free', 'Heart Care');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (8, 'Gluten Free', 'Appetite Stimulation');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (9, 'Organic', 'Dental Care');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (10, 'Grain Free', 'Digestive Health');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (11, 'Gluten Free', 'Hip&Joint Support');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (12, 'Sensitive Digestion', 'Dental Care&Breadth');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (13, 'Organic', 'Skin&Coat Health');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (14, 'Natural', 'Itch&Redness Remedy');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (15, 'Hypersensibil', 'Eye care');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (16, 'No corn/wheat/soy', 'Vitamins&Minerals');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (17, 'Gluten Free', 'Anti-Parasitic');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (18, 'No corn/wheat/soy', 'Immune Support');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (19, 'Gluten Free', 'Vitamins&Minerals');
INSERT INTO "products.health" (ProductID, SpecialDiet, HealthFeature) VALUES (20, 'Gluten Free', 'Immune Support');

INSERT INTO "products.health.food" (ProductID, Flavour, FoodForm, FoodCategory, Quantity) VALUES (1, 'Chicken', 'Dry Food', 'Dry Dog Food', 10);
INSERT INTO "products.health.food" (ProductID, Flavour, FoodForm, FoodCategory, Quantity) VALUES (2, 'Beef', 'Dry Food', 'Dry Dog Food', 12);
INSERT INTO "products.health.food" (ProductID, Flavour, FoodForm, FoodCategory, Quantity) VALUES (3, 'Beef', 'Dry Food', 'Premium Food', 5);
INSERT INTO "products.health.food" (ProductID, Flavour, FoodForm, FoodCategory, Quantity) VALUES (4, 'Lamb', 'Wet Food', 'Premium Food', 2);
INSERT INTO "products.health.food" (ProductID, Flavour, FoodForm, FoodCategory, Quantity) VALUES (5, 'Lamb', 'Wet Food', 'Veterinary Diets', 2.5);
INSERT INTO "products.health.food" (ProductID, Flavour, FoodForm, FoodCategory, Quantity) VALUES (6, 'Chicken', 'Raw Food', 'Veterinary Diets', 1.5);
INSERT INTO "products.health.food" (ProductID, Flavour, FoodForm, FoodCategory, Quantity) VALUES (7, 'Turkey', 'Raw Food', 'Premium Food', 0.5);
INSERT INTO "products.health.food" (ProductID, Flavour, FoodForm, FoodCategory, Quantity) VALUES (8, 'Chicken', 'Dehydrated Food', 'Treats', 0.5);
INSERT INTO "products.health.food" (ProductID, Flavour, FoodForm, FoodCategory, Quantity) VALUES (9, 'Beef', 'Dehydrated Food', 'Treats', 0.5);
INSERT INTO "products.health.food" (ProductID, Flavour, FoodForm, FoodCategory, Quantity) VALUES (10, 'Chicken', 'Canned Food', 'Treats', 1);

INSERT INTO "products.health.healthcare" (ProductID, ActiveIngredient, MedicationForm, MedicationType) VALUES (11, 'Glucosamine', 'Powder', 'non-prescription');
INSERT INTO "products.health.healthcare" (ProductID, ActiveIngredient, MedicationForm, MedicationType) VALUES (12, 'Vitamin B12', 'Soft Chew', 'non-prescription');
INSERT INTO "products.health.healthcare" (ProductID, ActiveIngredient, MedicationForm, MedicationType) VALUES (13, 'Omega 3', 'Solution', 'non-prescription');
INSERT INTO "products.health.healthcare" (ProductID, ActiveIngredient, MedicationForm, MedicationType) VALUES (14, 'Fish Oil', 'Spray', 'prescription');
INSERT INTO "products.health.healthcare" (ProductID, ActiveIngredient, MedicationForm, MedicationType) VALUES (15, 'Vitamin E', 'Ointment', 'prescription');
INSERT INTO "products.health.healthcare" (ProductID, ActiveIngredient, MedicationForm, MedicationType) VALUES (16, 'Calcium', 'Chewable Tablet', 'non-prescription');
INSERT INTO "products.health.healthcare" (ProductID, ActiveIngredient, MedicationForm, MedicationType) VALUES (17, 'Praziquantel', 'Spray', 'non-prescription');
INSERT INTO "products.health.healthcare" (ProductID, ActiveIngredient, MedicationForm, MedicationType) VALUES (18, 'Vitamin D', 'Soft Chew', 'non-prescription');
INSERT INTO "products.health.healthcare" (ProductID, ActiveIngredient, MedicationForm, MedicationType) VALUES (19, 'Glucosamine', 'Soft Chew', 'non-prescription');
INSERT INTO "products.health.healthcare" (ProductID, ActiveIngredient, MedicationForm, MedicationType) VALUES (20, 'Iron', 'Chewable Tablet', 'prescription');

INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (21, 'Tough Chewer', 'Leather', 'black');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (22, 'Stuffing-free', 'Cotton', 'white');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (23, 'Training', 'Wood', 'red');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (24, 'Exercise', 'Rope', 'orange');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (25, 'Water Toy', 'Plastic', 'green');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (26, 'Dental', 'Leather', 'blue');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (27, 'Indoor', 'Cotton', 'black');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (28, 'Fetching', 'Cotton', 'white');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (29, 'Exercise', 'Rope', 'red');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (30, 'Squeky', 'Plastic', 'orange');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (31, 'Waterproof', 'Microfiber', 'black');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (32, 'Adjustable', 'Leather', 'red');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (33, 'Training', 'Microfiber', 'blue');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (34, 'Outdoor', 'Leather', 'brown');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (35, 'Reflective', 'Neoprene', 'yellow');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (36, 'Detangling', 'Wood', 'brown');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (37, 'Shed Control', 'Plastic', 'blue');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (38, 'Hypoallergenic', 'Gel', 'white');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (39, 'Medicated', 'Cream', 'white');
INSERT INTO "products.supplies" (ProductID, Features, Material, Colour) VALUES (40, 'Cruelty-Free', 'Steel', 'green');

INSERT INTO "products.supplies.grooming" (ProductID, Category, HealthFeature) VALUES (36, 'Brushes&Combs', 'Skin&Coat Health');
INSERT INTO "products.supplies.grooming" (ProductID, Category, HealthFeature) VALUES (37, 'Grooming Tools', 'Shedding control');
INSERT INTO "products.supplies.grooming" (ProductID, Category, HealthFeature) VALUES (38, 'Shampoos', 'Skin&Coat Health');
INSERT INTO "products.supplies.grooming" (ProductID, Category, HealthFeature) VALUES (39, 'Ointment', 'Calming');
INSERT INTO "products.supplies.grooming" (ProductID, Category, HealthFeature) VALUES (40, 'Nail Clipper', 'Nail&Paw Care');

INSERT INTO "products.supplies.leashes" (ProductID, LeashType, LeashLength) VALUES (31, 'Rectractable', 1);
INSERT INTO "products.supplies.leashes" (ProductID, LeashType, LeashLength) VALUES (32, 'Adjustable', 1);
INSERT INTO "products.supplies.leashes" (ProductID, LeashType, LeashLength) VALUES (33, 'Step in', 3);
INSERT INTO "products.supplies.leashes" (ProductID, LeashType, LeashLength) VALUES (34, 'Hands-free', 2);
INSERT INTO "products.supplies.leashes" (ProductID, LeashType, LeashLength) VALUES (35, 'Double Leash', 2);

INSERT INTO "products.supplies.toys" (ProductID, ToyCategory, Lifestage, Collection) VALUES (21, 'Chew Toys', 'Puppy', 'Star Wars');
INSERT INTO "products.supplies.toys" (ProductID, ToyCategory, Lifestage, Collection) VALUES (22, 'Plush Toys', 'Adult', 'Marvel');
INSERT INTO "products.supplies.toys" (ProductID, ToyCategory, Lifestage, Collection) VALUES (23, 'Fetch Toys', 'Senior', 'DC Comics');
INSERT INTO "products.supplies.toys" (ProductID, ToyCategory, Lifestage, Collection) VALUES (24, 'Rope Toys', 'Adult', 'Disney');
INSERT INTO "products.supplies.toys" (ProductID, ToyCategory, Lifestage, Collection) VALUES (25, 'Interactive Toys', 'Adult', 'Warner Bros');
INSERT INTO "products.supplies.toys" (ProductID, ToyCategory, Lifestage, Collection) VALUES (26, 'Chew Toys', 'Puppy', 'Star Wars');
INSERT INTO "products.supplies.toys" (ProductID, ToyCategory, Lifestage, Collection) VALUES (27, 'Plush Toys', 'Puppy', 'Marvel');
INSERT INTO "products.supplies.toys" (ProductID, ToyCategory, Lifestage, Collection) VALUES (28, 'Fetch Toys', 'Adult', 'DC Comics');
INSERT INTO "products.supplies.toys" (ProductID, ToyCategory, Lifestage, Collection) VALUES (29, 'Rope Toys', 'Senior', 'Disney');
INSERT INTO "products.supplies.toys" (ProductID, ToyCategory, Lifestage, Collection) VALUES (30, 'Interactive Toys', 'Senior', 'Warner Bros');

INSERT INTO special_diet (id, special_diet) VALUES (1, 'Gluten Free');
INSERT INTO special_diet (id, special_diet) VALUES (2, 'High Protein');
INSERT INTO special_diet (id, special_diet) VALUES (3, 'No corn/wheat/soy');
INSERT INTO special_diet (id, special_diet) VALUES (4, 'Sensitive Digestion');
INSERT INTO special_diet (id, special_diet) VALUES (5, 'Grain Free');
INSERT INTO special_diet (id, special_diet) VALUES (6, 'Organic');
INSERT INTO special_diet (id, special_diet) VALUES (7, 'Hypersensibil');
INSERT INTO special_diet (id, special_diet) VALUES (8, 'Natural');

INSERT INTO supply_colour (id, colour) VALUES (1, 'black');
INSERT INTO supply_colour (id, colour) VALUES (2, 'white');
INSERT INTO supply_colour (id, colour) VALUES (3, 'red');
INSERT INTO supply_colour (id, colour) VALUES (4, 'orange');
INSERT INTO supply_colour (id, colour) VALUES (5, 'green');
INSERT INTO supply_colour (id, colour) VALUES (6, 'blue');
INSERT INTO supply_colour (id, colour) VALUES (7, 'brown');
INSERT INTO supply_colour (id, colour) VALUES (8, 'yellow');

INSERT INTO supply_feature (id, feature) VALUES (1, 'Tough Chewer');
INSERT INTO supply_feature (id, feature) VALUES (2, 'Stuffing-free');
INSERT INTO supply_feature (id, feature) VALUES (3, 'Training');
INSERT INTO supply_feature (id, feature) VALUES (4, 'Exercise');
INSERT INTO supply_feature (id, feature) VALUES (5, 'Water Toy');
INSERT INTO supply_feature (id, feature) VALUES (6, 'Dental');
INSERT INTO supply_feature (id, feature) VALUES (7, 'Indoor');
INSERT INTO supply_feature (id, feature) VALUES (8, 'Fetching');
INSERT INTO supply_feature (id, feature) VALUES (9, 'Squeky');
INSERT INTO supply_feature (id, feature) VALUES (10, 'Waterproof');
INSERT INTO supply_feature (id, feature) VALUES (11, 'Adjustable');
INSERT INTO supply_feature (id, feature) VALUES (12, 'Outdoor');
INSERT INTO supply_feature (id, feature) VALUES (13, 'Reflective');
INSERT INTO supply_feature (id, feature) VALUES (14, 'Detangling');
INSERT INTO supply_feature (id, feature) VALUES (15, 'Shed Control');
INSERT INTO supply_feature (id, feature) VALUES (16, 'Hypoallergenic');
INSERT INTO supply_feature (id, feature) VALUES (17, 'Medicated');
INSERT INTO supply_feature (id, feature) VALUES (18, 'Cruelty-Free');

INSERT INTO supply_material (id, material) VALUES (1, 'Leather');
INSERT INTO supply_material (id, material) VALUES (2, 'Cotton');
INSERT INTO supply_material (id, material) VALUES (3, 'Wood');
INSERT INTO supply_material (id, material) VALUES (4, 'Rope');
INSERT INTO supply_material (id, material) VALUES (5, 'Plastic');
INSERT INTO supply_material (id, material) VALUES (6, 'Microfiber');
INSERT INTO supply_material (id, material) VALUES (7, 'Neoprene');
INSERT INTO supply_material (id, material) VALUES (8, 'Gel');
INSERT INTO supply_material (id, material) VALUES (9, 'Cream');
INSERT INTO supply_material (id, material) VALUES (10, 'Steel');

INSERT INTO toy_type (id, type) VALUES (1, 'Chew Toys');
INSERT INTO toy_type (id, type) VALUES (2, 'Plush Toys');
INSERT INTO toy_type (id, type) VALUES (3, 'Fetch Toys');
INSERT INTO toy_type (id, type) VALUES (4, 'Rope Toys');
INSERT INTO toy_type (id, type) VALUES (5, 'Interactive Toys');

