INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (12, 'Anti-Parasitic');
INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (6, 'Appetite Stimulation');
INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (15, 'Calming');
INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (8, 'Dental Care&Breadth');
INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (5, 'Digestive Health');
INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (10, 'Eye care');
INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (7, 'Heart Care');
INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (3, 'High-Energy');
INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (1, 'Hip&Joint Support');
INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (13, 'Immune Support');
INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (9, 'Itch&Redness Remedy');
INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (16, 'Nail&Paw Care');
INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (14, 'Shedding control');
INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (2, 'Skin&Coat Health');
INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (11, 'Vitamins&Minerals');
INSERT INTO petshop.c_health_feature (id, health_feature) VALUES (4, 'Weight Management');