INSERT INTO petshop.country (id, country_name, iso_code) VALUES (238, 'AFGHANISTAN', 'AF');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (239, 'ALBANIA', 'AL');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (240, 'ALGERIA', 'DZ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (241, 'AMERICAN SAMOA', 'AS');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (242, 'ANDORRA', 'AD');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (243, 'ANGOLA', 'AO');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (244, 'ANTARCTICA', 'AQ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (245, 'ANTIGUA AND BARBUDA', 'AG');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (246, 'ARGENTINA', 'AR');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (247, 'ARMENIA', 'AM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (248, 'ARUBA', 'AW');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (249, 'AUSTRALIA', 'AU');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (250, 'AUSTRIA', 'AT');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (251, 'AZERBAIJAN', 'AZ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (252, 'BAHAMAS', 'BS');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (253, 'BAHRAIN', 'BH');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (254, 'BANGLADESH', 'BD');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (255, 'BARBADOS', 'BB');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (256, 'BELARUS', 'BY');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (257, 'BELGIUM', 'BE');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (258, 'BELIZE', 'BZ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (259, 'BENIN', 'BJ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (260, 'BERMUDA', 'BM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (261, 'BHUTAN', 'BT');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (262, 'BOLIVIA', 'BO');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (263, 'BOSNIA AND HERZEGOVINA', 'BA');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (264, 'BOTSWANA', 'BW');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (265, 'BOUVET ISLAND', 'BV');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (266, 'BRAZIL', 'BR');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (267, 'BRITISH INDIAN OCEAN TERRITORY', 'IO');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (268, 'BRUNEI DARUSSALAM', 'BN');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (269, 'BULGARIA', 'BG');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (270, 'BURKINA FASO', 'BF');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (271, 'BURUNDI', 'BI');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (272, 'CAMBODIA', 'KH');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (273, 'CAMEROON', 'CM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (274, 'CANADA', 'CA');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (275, 'CAPE VERDE', 'CV');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (276, 'CAYMAN ISLANDS', 'KY');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (277, 'CENTRAL AFRICAN REPUBLIC', 'CF');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (278, 'CHAD', 'TD');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (279, 'CHILE', 'CL');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (280, 'CHINA', 'CN');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (281, 'CHRISTMAS ISLAND', 'CX');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (282, 'COCOS (KEELING) ISLANDS', 'CC');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (283, 'COLOMBIA', 'CO');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (284, 'COMOROS', 'KM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (285, 'CONGO', 'CG');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (286, 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'CD');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (287, 'COOK ISLANDS', 'CK');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (288, 'COSTA RICA', 'CR');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (289, 'COTE D''IVOIRE', 'CI');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (290, 'CROATIA', 'HR');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (291, 'CUBA', 'CU');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (292, 'CYPRUS', 'CY');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (293, 'CZECH REPUBLIC', 'CZ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (294, 'DENMARK', 'DK');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (295, 'DJIBOUTI', 'DJ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (296, 'DOMINICA', 'DM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (297, 'DOMINICAN REPUBLIC', 'DO');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (298, 'ECUADOR', 'EC');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (299, 'EGYPT', 'EG');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (300, 'EL SALVADOR', 'SV');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (301, 'EQUATORIAL GUINEA', 'GQ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (302, 'ERITREA', 'ER');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (303, 'ESTONIA', 'EE');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (304, 'ETHIOPIA', 'ET');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (305, 'FALKLAND ISLANDS (MALVINAS)', 'FK');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (306, 'FAROE ISLANDS', 'FO');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (307, 'FIJI', 'FJ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (308, 'FINLAND', 'FI');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (309, 'FRANCE', 'FR');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (310, 'FRENCH GUIANA', 'GF');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (311, 'FRENCH POLYNESIA', 'PF');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (312, 'FRENCH SOUTHERN TERRITORIES', 'TF');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (313, 'GABON', 'GA');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (314, 'GAMBIA', 'GM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (315, 'GEORGIA', 'GE');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (316, 'GERMANY', 'DE');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (317, 'GHANA', 'GH');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (318, 'GIBRALTAR', 'GI');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (319, 'GREECE', 'GR');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (320, 'GREENLAND', 'GL');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (321, 'GRENADA', 'GD');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (322, 'GUADELOUPE', 'GP');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (323, 'GUAM', 'GU');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (324, 'GUATEMALA', 'GT');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (325, 'GUINEA', 'GN');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (326, 'GUINEA-BISSAU', 'GW');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (327, 'GUYANA', 'GY');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (328, 'HAITI', 'HT');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (329, 'HEARD ISLAND AND MCDONALD ISLANDS', 'HM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (330, 'HONDURAS', 'HN');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (331, 'HONG KONG', 'HK');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (332, 'HUNGARY', 'HU');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (333, 'ICELAND', 'IS');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (334, 'INDIA', 'IN');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (335, 'INDONESIA', 'ID');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (336, 'IRAN, ISLAMIC REPUBLIC OF', 'IR');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (337, 'IRAQ', 'IQ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (338, 'IRELAND', 'IE');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (339, 'ISRAEL', 'IL');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (340, 'ITALY', 'IT');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (341, 'JAMAICA', 'JM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (342, 'JAPAN', 'JP');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (343, 'JORDAN', 'JO');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (344, 'KAZAKHSTAN', 'KZ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (345, 'KENYA', 'KE');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (346, 'KIRIBATI', 'KI');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (347, 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 'KP');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (348, 'KOREA, REPUBLIC OF', 'KR');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (349, 'KUWAIT', 'KW');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (350, 'KYRGYZSTAN', 'KG');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (351, 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'LA');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (352, 'LATVIA', 'LV');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (353, 'LEBANON', 'LB');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (354, 'LESOTHO', 'LS');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (355, 'LIBERIA', 'LR');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (356, 'LIBYAN ARAB JAMAHIRIYA', 'LY');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (357, 'LIECHTENSTEIN', 'LI');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (358, 'LITHUANIA', 'LT');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (359, 'LUXEMBOURG', 'LU');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (360, 'MACAO', 'MO');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (361, 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'MK');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (362, 'MADAGASCAR', 'MG');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (363, 'MALAWI', 'MW');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (364, 'MALAYSIA', 'MY');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (365, 'MALDIVES', 'MV');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (366, 'MALI', 'ML');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (367, 'MALTA', 'MT');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (368, 'MARSHALL ISLANDS', 'MH');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (369, 'MARTINIQUE', 'MQ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (370, 'MAURITANIA', 'MR');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (371, 'MAURITIUS', 'MU');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (372, 'MAYOTTE', 'YT');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (373, 'MEXICO', 'MX');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (374, 'MICRONESIA, FEDERATED STATES OF', 'FM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (375, 'MOLDOVA, REPUBLIC OF', 'MD');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (376, 'MONACO', 'MD');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (377, 'MONGOLIA', 'MN');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (378, 'MONTSERRAT', 'MS');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (379, 'MOROCCO', 'MA');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (380, 'MOZAMBIQUE', 'MZ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (381, 'MYANMAR', 'MM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (382, 'NAMIBIA', 'NA');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (383, 'NAURU', 'NR');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (384, 'NEPAL', 'NP');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (385, 'NETHERLANDS', 'NL');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (386, 'NETHERLANDS ANTILLES', 'AN');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (387, 'NEW CALEDONIA', 'NC');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (388, 'NEW ZEALAND', 'NZ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (389, 'NICARAGUA', 'NI');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (390, 'NIGER', 'NE');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (391, 'NIGERIA', 'NG');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (392, 'NIUE', 'NU');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (393, 'NORFOLK ISLAND', 'NF');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (394, 'NORTHERN MARIANA ISLANDS', 'MP');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (395, 'NORWAY', 'NO');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (396, 'OMAN', 'OM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (397, 'PAKISTAN', 'PK');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (398, 'PALAU', 'PW');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (399, 'PALESTINIAN TERRITORY, OCCUPIED', 'PS');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (400, 'PANAMA', 'PA');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (401, 'PAPUA NEW GUINEA', 'PG');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (402, 'PARAGUAY', 'PY');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (403, 'PERU', 'PE');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (404, 'PHILIPPINES', 'PH');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (405, 'PITCAIRN', 'PN');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (406, 'POLAND', 'PL');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (407, 'PUERTO RICO', 'PR');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (408, 'QATAR', 'QA');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (409, 'R�UNION', 'RE');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (410, 'ROMANIA', 'RO');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (411, 'RUSSIAN FEDERATION', 'RU');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (412, 'RWANDA', 'RW');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (413, 'SAINT HELENA', 'SH');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (414, 'SAINT KITTS AND NEVIS', 'KN');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (415, 'SAINT LUCIA', 'LC');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (416, 'SAINT PIERRE AND MIQUELON', 'PM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (417, 'SAINT VINCENT AND THE GRENADINES', 'VC');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (418, 'SAMOA', 'WS');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (419, 'SAN MARINO', 'SM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (420, 'SAO TOME AND PRINCIPE', 'ST');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (421, 'SAUDI ARABIA', 'SA');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (422, 'SENEGAL', 'SN');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (423, 'SERBIA AND MONTENEGRO', 'CS');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (424, 'SEYCHELLES', 'SC');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (425, 'SIERRA LEONE', 'SL');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (426, 'SINGAPORE', 'SG');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (427, 'SLOVAKIA', 'SK');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (428, 'SLOVENIA', 'SI');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (429, 'SOLOMON ISLANDS', 'SB');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (430, 'SOMALIA', 'SO');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (431, 'SOUTH AFRICA', 'ZA');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (432, 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'GS');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (433, 'SPAIN', 'ES');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (434, 'SRI LANKA', 'LK');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (435, 'SUDAN', 'SD');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (436, 'SURINAME', 'SR');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (437, 'SVALBARD AND JAN MAYEN', 'SJ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (438, 'SWAZILAND', 'SZ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (439, 'SWEDEN', 'SE');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (440, 'SWITZERLAND', 'CH');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (441, 'SYRIAN ARAB REPUBLIC', 'SY');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (442, 'TAIWAN, PROVINCE OF CHINA', 'TW');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (443, 'TAJIKISTAN', 'TJ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (444, 'TANZANIA, UNITED REPUBLIC OF', 'TZ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (445, 'THAILAND', 'TH');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (446, 'TIMOR-LESTE', 'TL');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (447, 'TOGO', 'TG');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (448, 'TOKELAU', 'TK');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (449, 'TONGA', 'TO');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (450, 'TRINIDAD AND TOBAGO', 'TT');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (451, 'TUNISIA', 'TN');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (452, 'TURKEY', 'TR');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (453, 'TURKMENISTAN', 'TM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (454, 'TURKS AND CAICOS ISLANDS', 'TC');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (455, 'TUVALU', 'TV');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (456, 'UGANDA', 'UG');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (457, 'UKRAINE', 'UA');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (458, 'UNITED ARAB EMIRATES', 'AE');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (459, 'UNITED KINGDOM', 'GB');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (460, 'UNITED STATES', 'US');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (461, 'UNITED STATES MINOR OUTLYING ISLANDS', 'UM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (462, 'URUGUAY', 'UY');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (463, 'UZBEKISTAN', 'UZ');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (464, 'VANUATU', 'VU');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (465, 'VENEZUELA', 'VE');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (466, 'VIET NAM', 'VN');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (467, 'VIRGIN ISLANDS, BRITISH', 'VG');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (468, 'VIRGIN ISLANDS, U.S.', 'VI');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (469, 'WALLIS AND FUTUNA', 'WF');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (470, 'WESTERN SAHARA', 'EH');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (471, 'YEMEN', 'YE');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (472, 'ZAMBIA', 'ZM');
INSERT INTO petshop.country (id, country_name, iso_code) VALUES (473, 'ZIMBABWE', 'ZW');