INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (1, 'Dry Dog Food', 120, 1, 1, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (2, 'Dehydrated Dog Food', 150, 2, 2, 5);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (3, 'Purina Pro Plan', 210, 1, 3, 5);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (4, 'Premium Dry Dog Food', 145, 1, 4, 5);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (5, 'Wet Dog Food Variety', 80, 2, 5, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (6, 'Hill''s Science Diet', 65, 1, 5, 3);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (7, 'Turkey Chunks Raw Dog Food', 95, 2, 3, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (8, 'Dehydrated Dog Food', 25, 1, 2, 2);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (9, 'Divine Delights', 30, 1, 1, 3);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (10, 'Mediterranean Style Canned Dog Food', 25, 2, 3, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (11, 'HeartGuard Plus Powder Supplements', 45, 1, 6, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (12, 'DentaLife Dentastix Chewable Treats', 34, 1, 2, 5);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (13, 'First-Aid Pet Spray', 25, 1, 2, 3);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (14, 'Wound & Skin Hydrogel Pet Cream', 60, 2, 3, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (15, 'First-Aid Pet Spray Eye Protection', 80, 1, 4, 5);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (16, 'MultiVitamin Dog Supplement', 50, 1, 5, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (17, 'Ear-Mite Protection', 30, 2, 7, 2);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (18, 'Canine Health Chewable Tablets', 35, 1, 2, 3);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (19, 'Dewormer Chewable Tablet', 20, 1, 1, 3);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (20, 'Essential Vitamins&Minerals Supplement', 25, 2, 7, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (21, 'Ring Dog Chew Toy', 30, 1, 8, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (22, 'Snuggle Plush Pet Toy', 25, 1, 9, 3);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (23, 'Rubber Ball', 35, 1, 2, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (24, 'Leather Rope Toy', 24, 1, 1, 2);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (25, 'Frisbee Dog Toy', 10, 1, 7, 3);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (26, 'Teething Pacifier Puppy Chew Toy', 20, 2, 3, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (27, 'Plush Teddy Bear Toy', 30, 1, 4, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (28, 'Indoor Ball Dog Toy', 40, 1, 5, 5);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (29, 'Plush With Inside Rope Toy', 25, 1, 7, 3);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (30, 'Activity Flip Board Strategy Dog Toy', 15, 2, 8, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (31, 'Rectractable Leash', 50, 1, 7, 5);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (32, 'Adjustable Trainer Leash', 45, 1, 2, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (33, 'Comfortable Leash', 60, 1, 1, 2);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (34, 'Reflective Rope Dog Leash', 80, 2, 7, 3);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (35, 'Ultrasecure Leash', 65, 1, 8, 3);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (36, 'Groomer''s Best Brush', 20, 2, 2, 3);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (37, 'Hand Gloves Deshedding Aid', 15, 1, 3, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (38, 'Lavender&Mint Shampoo', 25, 1, 4, 4);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (39, 'Aloe Vera Ointment for Dogs', 30, 1, 1, 5);
INSERT INTO petshop.product (product_id, product_name, price, availability_id, brand_id, customer_rating) VALUES (40, 'Best Nail Clipper for Dogs', 35, 2, 7, 3);